<?php

/**
 * @file
 * Contains bella.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bella_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bella module.
    case 'help.page.bella':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This is my custom module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bella_theme() {
  return [
    'bella' => [
      'render element' => 'children',
    ],
  ];
}
