<?php

/**
 * @file
 * Contains ffw_custom.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ffw_custom_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ffw_custom module.
    case 'help.page.ffw_custom':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ffw_custom_theme() {
  return [
    'ffw_custom' => [
      'render element' => 'children',
    ],
  ];
}
